### ISSUE TITLE
Duplicate island

### ISSUE THREAD

**Issue by viktor-ferenczi** [Jerodar/WAMap#2]
SE3 and SE4: Cloverleaf

I think the one in SE3 is named "Raised Quarter". The SE4 one is Cloverleaf.

**Comment by Jerodar** [comment]
Yeah this was the only duplicate island I found so far. But judging by the screenshots I took at the time they are both the same cloverleaf island. 
It is possible though that I mixed up the screenshots itself, does the Se3 island look different then on the map? And if so could you send me a screenshot of it? Thanks!

**Comment by Jerodar** [comment]
The map with these islands is no longer in use.
